# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f77ecdd5186ccbe10e8b060b9fb5b0d233387fa4a2b335f4037cb2774b2034c56afed412e973a2e4eaa0c29fe22f7c1db0eb903cb580fa948cc06a11616f4b80

test:
  secret_key_base: 45f617a41222c82306f938a598ea3d93c2b2041e4150cd0755f56937ccd2b01aa971192350e3b4cc17de837f81d2220bf42309da5ccafb0c0fb51bc6981ae418

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
